# Generated by Django 4.2.5 on 2023-09-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='document_number',
            field=models.IntegerField(null=True, verbose_name='Número del documento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='document_type',
            field=models.CharField(choices=[('1', 'Cedula'), ('2', 'Pasaporte'), ('3', 'Visa'), ('4', 'Otro')], max_length=1, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='country',
            field=models.CharField(max_length=50, verbose_name='País de nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=50, verbose_name='Genero'),
        ),
    ]
