# Generated by Django 4.2.5 on 2023-09-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_persona_gender_alter_persona_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='status',
            field=models.CharField(choices=[('1', 'Soltero'), ('2', 'Casado'), ('3', 'Unión libre'), ('5', 'Separado'), ('6', 'Divorciado'), ('7', 'Viudo')], max_length=1, verbose_name='Estado civíl'),
        ),
    ]
