# Generated by Django 4.2.5 on 2023-09-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_persona_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='document_number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Número del documento'),
        ),
    ]
