# Generated by Django 4.2.5 on 2023-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_persona_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='status',
            field=models.CharField(choices=[('1', 'Soltero'), ('2', 'Casado'), ('3', 'Unión libre'), ('4', 'Separado'), ('5', 'Divorciado'), ('6', 'Viudo')], max_length=1, verbose_name='Estado civíl'),
        ),
    ]
